-- 006_insights.sql
-- Behavioral insights generated by edge functions

do $$ begin
  create type insight_type as enum (
    'peak_window',
    'workflow_pattern',
    'skill_detection',
    'productivity_trend',
    'burnout_risk',
    'category_success'
  );
exception when duplicate_object then null; end $$;

create table if not exists public.insights (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  type insight_type not null,
  title varchar(255) not null,
  description text,
  metric_value numeric(10,2),
  metric_unit varchar(50),
  metric_metadata jsonb,
  confidence numeric(4,2) check (confidence is null or confidence between 0 and 1),
  data_points int default 0,
  recommended_action text,
  generated_for_week date,
  valid_from timestamptz not null default now(),
  valid_until timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_insights_user_created
  on public.insights (user_id, created_at desc);

create index if not exists idx_insights_user_type
  on public.insights (user_id, type);

create index if not exists idx_insights_user_week
  on public.insights (user_id, generated_for_week desc);

comment on table public.insights is 'Behavioral insights generated weekly. metric_metadata stores type-specific payload.';
