-- 041_webhooks.sql
-- T-WEBHOOKS: Partner webhook system for outbound event delivery +
-- inbound closed-loop callbacks. Adds 3 new tables and 1 helper function.
--
-- Strictly additive. No edits to 001–040 migrations. Every DDL uses
-- `if not exists` / `or replace` / guarded `do` blocks, so the file is
-- safe to re-apply.
--
-- IMPORTANT: 041, not 040. D-1 (status page) and D-3 (this) both need a
-- 040 number; D-3 bumped to 041 to avoid the collision. The user must
-- resolve the final numbering before commit (see the open-items table
-- in docs/webhooks.md).
--
-- ============================================================================
-- Outbound event types (7 documented in the design doc, 8 actually seeded)
-- ============================================================================
--   1. credential.issued       — a new W3C verifiable credential was issued
--   2. credential.revoked      — a W3C verifiable credential was revoked
--   3. placement.predicted     — a new placement prediction was generated
--   4. student.connected       — a student opted in to a company connection
--   5. cohort.report_ready     — a cohort-level analytics report is ready
--   6. job_match.created       — a recruiter created a job match for a student
--   7. nudge.sent              — a nudge was successfully delivered
--   8. nudge.failed            — a nudge could not be delivered
--
-- Inbound event types (received via webhook-receiver):
--   a. placement.outcome       — the student got placed, here's the ground truth
--   b. credential.viewed       — a third-party viewed a credential (analytics)
--   c. student.engagement      — an external LMS / portal is reporting engagement
--
-- ============================================================================
-- 1. public.webhook_endpoints — partner-registered outbound endpoints
-- ============================================================================
-- `owner_user_id` is the Antarix user who registered the endpoint; the
-- three possible `owner_type` values describe their role at the moment of
-- registration. `secret` is 32 bytes of crypto-grade randomness hex-encoded
-- (64 chars) — generated by the future webhook-create Edge Function and
-- returned to the partner exactly ONCE. The dispatcher signs every POST
-- with HMAC-SHA256(secret, "${t}.${body}") where t is a unix timestamp.
--
-- `consecutive_failures` is reset on every success and incremented on
-- every 5xx / timeout / network error. At 10 it auto-disables the
-- endpoint (sets is_active = false) and a warn-log is emitted by the
-- dispatcher.

create table if not exists public.webhook_endpoints (
  id                    uuid primary key default gen_random_uuid(),
  owner_user_id         uuid not null references public.users(id) on delete cascade,
  owner_type            text not null,
  url                   text not null,
  secret                text not null,
  subscribed_events     text[] not null default '{}',
  is_active             boolean not null default true,
  created_at            timestamptz not null default now(),
  last_success_at       timestamptz,
  last_failure_at       timestamptz,
  consecutive_failures  integer not null default 0,
  description           text,
  constraint webhook_endpoints_owner_type_chk
    check (owner_type in ('company', 'institution', 'partner'))
);

-- Defensive idempotent column adds so a partial earlier apply still converges.
alter table public.webhook_endpoints
  add column if not exists owner_user_id        uuid references public.users(id) on delete cascade;
alter table public.webhook_endpoints
  add column if not exists owner_type           text;
alter table public.webhook_endpoints
  add column if not exists url                  text;
alter table public.webhook_endpoints
  add column if not exists secret               text;
alter table public.webhook_endpoints
  add column if not exists subscribed_events    text[] not null default '{}';
alter table public.webhook_endpoints
  add column if not exists is_active            boolean not null default true;
alter table public.webhook_endpoints
  add column if not exists created_at           timestamptz not null default now();
alter table public.webhook_endpoints
  add column if not exists last_success_at      timestamptz;
alter table public.webhook_endpoints
  add column if not exists last_failure_at      timestamptz;
alter table public.webhook_endpoints
  add column if not exists consecutive_failures integer not null default 0;
alter table public.webhook_endpoints
  add column if not exists description          text;

-- The owner_type check is not re-declared; the constraint already exists
-- from `create table if not exists` above. Re-apply is a no-op because
-- PG skips the create when the table is already there.

-- Useful indexes for the dispatcher's hot query:
--   `where is_active = true and subscribed_events @> array[event_type]`
-- The GIN on subscribed_events supports the @> (contains) operator.
create index if not exists webhook_endpoints_is_active_idx
  on public.webhook_endpoints(is_active)
  where is_active = true;

create index if not exists webhook_endpoints_subscribed_events_gin
  on public.webhook_endpoints using gin (subscribed_events);

create index if not exists webhook_endpoints_owner_user_idx
  on public.webhook_endpoints(owner_user_id);

alter table public.webhook_endpoints enable row level security;
-- No policies: partner CRUD is via authenticated Edge Functions (future
-- webhook-create / -list / -update / -delete). The dispatcher and receiver
-- always use the service-role client. anon and authenticated are denied.

-- ============================================================================
-- 2. public.webhook_deliveries — append-only delivery log
-- ============================================================================
-- One row per dispatch attempt. The dispatcher INSERTs a 'pending' row
-- first to obtain a `delivery.id` for the X-Antarix-Delivery-Id header,
-- then UPDATEs the row to its terminal state. The retry cron
-- (`retryFailedDeliveries`) finds rows in the 'failed' state and
-- re-dispatches with attempt_number + 1.
--
-- `payload` is the exact bytes we signed; the partner can replay this
-- to verify a delivery without re-firing. `response_body_excerpt` is
-- truncated to 2KB so a partner error response can't bloat the row.

create table if not exists public.webhook_deliveries (
  id                     uuid primary key default gen_random_uuid(),
  endpoint_id            uuid not null references public.webhook_endpoints(id) on delete cascade,
  event_type             text not null,
  event_id               uuid not null,
  payload                jsonb not null,
  attempt_number         integer not null default 1,
  status                 text not null,
  response_status        integer,
  response_body_excerpt  text,
  error_message          text,
  requested_at           timestamptz not null default now(),
  responded_at           timestamptz,
  constraint webhook_deliveries_status_chk
    check (status in ('pending', 'succeeded', 'failed', 'exhausted'))
);

alter table public.webhook_deliveries
  add column if not exists endpoint_id            uuid references public.webhook_endpoints(id) on delete cascade;
alter table public.webhook_deliveries
  add column if not exists event_type             text;
alter table public.webhook_deliveries
  add column if not exists event_id               uuid;
alter table public.webhook_deliveries
  add column if not exists payload                jsonb;
alter table public.webhook_deliveries
  add column if not exists attempt_number         integer not null default 1;
alter table public.webhook_deliveries
  add column if not exists status                 text;
alter table public.webhook_deliveries
  add column if not exists response_status        integer;
alter table public.webhook_deliveries
  add column if not exists response_body_excerpt  text;
alter table public.webhook_deliveries
  add column if not exists error_message          text;
alter table public.webhook_deliveries
  add column if not exists requested_at           timestamptz not null default now();
alter table public.webhook_deliveries
  add column if not exists responded_at           timestamptz;

-- The retry cron scans by (status, attempt_number, requested_at); the
-- diagnostic queries from the future v2 web UI sort by requested_at desc.
create index if not exists webhook_deliveries_retry_idx
  on public.webhook_deliveries(status, attempt_number, requested_at)
  where status = 'failed';

create index if not exists webhook_deliveries_endpoint_idx
  on public.webhook_deliveries(endpoint_id, requested_at desc);

create index if not exists webhook_deliveries_event_id_idx
  on public.webhook_deliveries(event_id);

alter table public.webhook_deliveries enable row level security;
-- No policies. Service-role only. The retry cron is a service-role caller;
-- partners read their own deliveries via a future webhook-list-deliveries
-- Edge Function (out of scope v1; see docs/webhooks.md §Open items).

-- ============================================================================
-- 3. public.webhook_event_types — reference table for event-type metadata
-- ============================================================================
-- The event_type string is the contract; the JSON Schema in `schema` is
-- a machine-readable description of the payload shape. We use Draft
-- 2020-12 (the same $schema as our OpenAPI spec, see 003-engage-and-showcase).
--
-- The dispatcher and the future /api/webhooks/event-types endpoint both
-- read from this table; nothing else hard-codes the event vocabulary.

create table if not exists public.webhook_event_types (
  event_type   text primary key,
  description  text not null,
  schema       jsonb not null
);

alter table public.webhook_event_types
  add column if not exists event_type  text;
alter table public.webhook_event_types
  add column if not exists description text;
alter table public.webhook_event_types
  add column if not exists schema      jsonb;

alter table public.webhook_event_types enable row level security;
-- No policies. The future /api/webhooks/event-types endpoint uses the
-- service-role client; for now the dispatcher hard-codes the type union
-- (WebhookEventType in _shared/webhook-dispatch.ts) so the DB only needs
-- to know the metadata, not police the strings.

-- ----------------------------------------------------------------------------
-- Seed the 8 outbound event types.
-- ----------------------------------------------------------------------------
-- 1. credential.issued
insert into public.webhook_event_types (event_type, description, schema) values
  ('credential.issued', 'A new W3C verifiable credential was issued to a student.', '{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "CredentialIssued",
    "type": "object",
    "required": ["credential_id", "did", "issued_to_user_id", "issued_at"],
    "properties": {
      "credential_id":     { "type": "string", "format": "uuid" },
      "did":               { "type": "string", "pattern": "^did:web:antarix\\.app:c/[0-9a-f-]{36}$" },
      "issued_to_user_id": { "type": "string", "format": "uuid" },
      "issued_at":         { "type": "string", "format": "date-time" },
      "skill_focus":       { "type": "array", "items": { "type": "string" } },
      "overall_score":     { "type": "number", "minimum": 0, "maximum": 100 }
    },
    "additionalProperties": true
  }'::jsonb)
on conflict (event_type) do update
  set description = excluded.description, schema = excluded.schema;

-- 2. credential.revoked
insert into public.webhook_event_types (event_type, description, schema) values
  ('credential.revoked', 'A W3C verifiable credential was revoked.', '{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "CredentialRevoked",
    "type": "object",
    "required": ["credential_id", "did", "revoked_at", "reason"],
    "properties": {
      "credential_id": { "type": "string", "format": "uuid" },
      "did":           { "type": "string", "pattern": "^did:web:antarix\\.app:c/[0-9a-f-]{36}$" },
      "revoked_at":    { "type": "string", "format": "date-time" },
      "reason":        { "type": "string" }
    },
    "additionalProperties": true
  }'::jsonb)
on conflict (event_type) do update
  set description = excluded.description, schema = excluded.schema;

-- 3. placement.predicted
insert into public.webhook_event_types (event_type, description, schema) values
  ('placement.predicted', 'A new placement prediction was generated for a student.', '{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "PlacementPredicted",
    "type": "object",
    "required": ["student_user_id", "predicted_at", "predicted_tier"],
    "properties": {
      "student_user_id":      { "type": "string", "format": "uuid" },
      "predicted_at":         { "type": "string", "format": "date-time" },
      "predicted_tier":       { "enum": ["top", "high", "mid", "low", "unranked"] },
      "predicted_salary_inr": { "type": "integer", "minimum": 0 },
      "model_version":        { "type": "string" }
    },
    "additionalProperties": true
  }'::jsonb)
on conflict (event_type) do update
  set description = excluded.description, schema = excluded.schema;

-- 4. student.connected
insert into public.webhook_event_types (event_type, description, schema) values
  ('student.connected', 'A student opted in to a company connection.', '{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "StudentConnected",
    "type": "object",
    "required": ["student_user_id", "company_id", "connected_at"],
    "properties": {
      "student_user_id": { "type": "string", "format": "uuid" },
      "company_id":      { "type": "string", "format": "uuid" },
      "connected_at":    { "type": "string", "format": "date-time" },
      "consent_source":  { "type": "string" }
    },
    "additionalProperties": true
  }'::jsonb)
on conflict (event_type) do update
  set description = excluded.description, schema = excluded.schema;

-- 5. cohort.report_ready
insert into public.webhook_event_types (event_type, description, schema) values
  ('cohort.report_ready', 'A cohort-level analytics report is ready for download.', '{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "CohortReportReady",
    "type": "object",
    "required": ["cohort_id", "report_url", "ready_at"],
    "properties": {
      "cohort_id":    { "type": "string", "format": "uuid" },
      "report_url":   { "type": "string", "format": "uri" },
      "ready_at":     { "type": "string", "format": "date-time" },
      "report_kind":  { "type": "string" }
    },
    "additionalProperties": true
  }'::jsonb)
on conflict (event_type) do update
  set description = excluded.description, schema = excluded.schema;

-- 6. job_match.created
insert into public.webhook_event_types (event_type, description, schema) values
  ('job_match.created', 'A recruiter created a job match for a student.', '{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "JobMatchCreated",
    "type": "object",
    "required": ["match_id", "student_user_id", "recruiter_user_id", "job_id", "created_at"],
    "properties": {
      "match_id":          { "type": "string", "format": "uuid" },
      "student_user_id":   { "type": "string", "format": "uuid" },
      "recruiter_user_id": { "type": "string", "format": "uuid" },
      "job_id":            { "type": "string" },
      "created_at":        { "type": "string", "format": "date-time" },
      "score":             { "type": "number", "minimum": 0, "maximum": 1 }
    },
    "additionalProperties": true
  }'::jsonb)
on conflict (event_type) do update
  set description = excluded.description, schema = excluded.schema;

-- 7. nudge.sent
insert into public.webhook_event_types (event_type, description, schema) values
  ('nudge.sent', 'A nudge was successfully delivered to a student.', '{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "NudgeSent",
    "type": "object",
    "required": ["nudge_id", "student_user_id", "channel", "sent_at"],
    "properties": {
      "nudge_id":        { "type": "string", "format": "uuid" },
      "student_user_id": { "type": "string", "format": "uuid" },
      "channel":         { "enum": ["whatsapp", "push", "email", "in_app"] },
      "sent_at":         { "type": "string", "format": "date-time" }
    },
    "additionalProperties": true
  }'::jsonb)
on conflict (event_type) do update
  set description = excluded.description, schema = excluded.schema;

-- 8. nudge.failed
insert into public.webhook_event_types (event_type, description, schema) values
  ('nudge.failed', 'A nudge could not be delivered.', '{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "NudgeFailed",
    "type": "object",
    "required": ["nudge_id", "student_user_id", "channel", "failed_at", "error_code"],
    "properties": {
      "nudge_id":        { "type": "string", "format": "uuid" },
      "student_user_id": { "type": "string", "format": "uuid" },
      "channel":         { "enum": ["whatsapp", "push", "email", "in_app"] },
      "failed_at":       { "type": "string", "format": "date-time" },
      "error_code":      { "type": "string" }
    },
    "additionalProperties": true
  }'::jsonb)
on conflict (event_type) do update
  set description = excluded.description, schema = excluded.schema;

-- ============================================================================
-- 4. public.webhook_generate_secret() — 32-byte hex helper
-- ============================================================================
-- Returns a 64-character lowercase hex string (32 random bytes). Called
-- by the future webhook-create Edge Function so the secret is generated
-- server-side with the database's pgcrypto entropy, not from a
-- client-side crypto.getRandomValues call that could be patched by a
-- compromised Edge Function host.
--
-- Marked STABLE so it can be inlined into a SELECT in the create RPC.
-- SECURITY DEFINER is not needed here (no privileged access) but the
-- function still pins search_path per the repo convention.

create or replace function public.webhook_generate_secret()
returns text
language sql
volatile
set search_path = public
as $$
  select encode(gen_random_bytes(32), 'hex');
$$;

comment on function public.webhook_generate_secret() is
  'Generates a 32-byte hex-encoded webhook signing secret using pgcrypto entropy. Server-side only.';

-- ============================================================================
-- 5. 90-day retention sweep (one-off, safe to re-apply)
-- ============================================================================
-- The dispatcher appends a row per attempt; over time this table grows.
-- v1 has no cron for GC (we promised not to touch 029_cron_002.sql or
-- 038_cron_004.sql). The snippet below is a one-off deletion; the
-- recurring schedule is documented in docs/webhooks.md §Open items.
delete from public.webhook_deliveries
 where requested_at < now() - interval '90 days';
